### ISSUE TITLE
JSON value '0' of type NSNumber cannot be converted to NSString

### ISSUE THREAD

**Issue by Cheonsoon** [realtime-framework/RCTRealtimeMessagingIOS#2]
Calling of RCTRealtimeMessaging.RTConnect() can result in this Exception, and I found that it is in file RCTRealtimeMessagingIOS.js, line: 20 & 24, where id is a string and should be increase by 1 and convert it to string, like: this.id = instances++ + "";

**Comment by JoaoCaixinha** [comment]
Hi, yes you are right, the instance property id is a string and instances global var is a number, however javascript converts number to string, we didn’t found any exception but the approach you propose is correct.
Thank you and best regards   

João Caixinha
Realtime Framework

**Comment by Cheonsoon** [comment]
01 - Error in simulator using safari or chrome core
![01 - Error in simulator using safari or chrome core](https://cloud.githubusercontent.com/assets/1361794/10196368/242c8912-67c5-11e5-91d1-40ed3209ffff.png)

02 - typeof this.id is still number
![02 - typeof this.id is still number](https://cloud.githubusercontent.com/assets/1361794/10196367/2424324e-67c5-11e5-8e00-a9d2ba9ce1e5.png)

And I'm wondering why it happens to me but your's is ok >__<

**Comment by realtime-framework** [comment]
Hi @zhangqianxun, a new version fixing this issue was published in npm. Please update.
We're sorry for this inconvenience.

**Comment by Cheonsoon** [comment]
OK! @realtime-framework , I have noticed that^_^, and thanks for yours' help

**Comment by jparreira** [comment]
Great news @zhangqianxun. Does this mean Realtime is working for your React Native app? Please let me know what you think of it. How could we improve it?
Thanks for your time.

**Comment by Cheonsoon** [comment]
Yes! @jparreira , the chatting module in my RN app is still in initial development stage, and I will told you the full experience of the SDK after I complete it. ^_^

**Comment by jparreira** [comment]
Cool @zhangqianxun , looking forward to hearing from you.
