### ISSUE TITLE
Build Fails in XCode

### ISSUE THREAD

**Issue by davidsims9t** [realtime-framework/RCTRealtimeMessagingIOS#6]
Hello,

I followed your documentation, however, when I attempted to add the RCTRealtimeMessaging in XCode, my project failed to build. I'm using React Native 0.15.

Thanks

**Comment by JoaoCaixinha** [comment]
Hi #davidsims9t, can you tell more details about the build error on your project?

Thanks

**Comment by davidsims9t** [comment]
I can't unfortunately. There's no errors that I'm actually getting, it just fails.

**Comment by JoaoCaixinha** [comment]
can you please send a screen shot of xcode after the build fails?
Thanks

**Comment by realtime-framework** [comment]
Hi @davidsims9t, see if the fix for issue #8 solves your problem. Thanks.
Closing this for now.
